### ISSUE TITLE
[Starbot] Prevent author self-stars from counting toward a message being added to Starboard?

### ISSUE THREAD

**Issue by gregdan3** [GrantGryczan/web#2]
As an option, of course.

My server has been using starbot for a fairly long time, and it's done an excellent job. I very much appreciate the work, as do the other admins in the server.
That said, we've had a rule in place that disallows users starring their own posts (self-starring is lame if the goal is to have community-pinned posts), but that rule is frustrating to identify and police. Things slip by, and then we have frustrated users.

Any chance such a feature could be added?

**Comment by GrantGryczan** [comment]
I have servers which actually prefer to allow self-starring, but I can make a command that disables it. I'll comment and close the issue once I've done that.

**Comment by GrantGryczan** [comment]
Alright, you should be able to disable self-starring now with `>⭐selfstar`. You might want to enable Starbot's permission to manage messages so it can automatically remove the self-starred reactions.

**Comment by gregdan3** [comment]
Sweet. You're a hero. I especially love that it calls the person out for their crime.
