### ISSUE TITLE
There is no issue, I just wanna say thanks for making this, it's really cool!

### ISSUE THREAD

**Issue by Cobular** [GrantGryczan/web#23]
My friend sent me some of your datapacks, which we're going to use on our server now they're really neat, and then I saw your pipe thing. That's so useful, it's always a bit too much of a pita to get images into GitHub pages for image hosting, and it's never really been worth setting something up myself since I need to do it like twice a month at most, but when I do, this'll be a lot easier. Thanks for making this, it's really cool!

**Comment by GrantGryczan** [comment]
Haha, np!
