### ISSUE TITLE
Allow selection of multiple items by holding "Shift" 

### ISSUE THREAD

**Issue by MrPigeontheCoder** [GrantGryczan/web#47]
On most file explorers, if the user presses shift while selecting 2 files, every file between the two selected files will be selected as well. This would most likely improve user experience as a small Quality of Life change.

**Comment by MrPigeontheCoder** [comment]
Unless this is already a thing...

**Comment by GrantGryczan** [comment]
It is. You should probably check these things _before_ submitting an issue.
